---
title: "streetlight_sna_plots"
author: "Drew Walker"
date: "9/30/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(network)
library(igraph)
library(ergm)
library(sna)
library(statnet)
library(intergraph)
library(ggraph)
library(egor)
library(readxl)

```
# SNA 

```{r, alter_list}
alter_list <- read_csv("alter_attributes_SL.csv")
alter_list <- alter_list %>% 
  select(-X6,-X7)%>% 
  filter(!is.na(ego_ID))

edges_raw <- alter_list %>% select(from=alter_ID,to=ego_ID,weight=alter.clo)


nodes_vols <- edges_raw %>% 
  mutate(ego_ID = paste0("Vol",from)) %>% 
  distinct(ego_ID)

edges <- edges_raw %>%
  mutate(alter_ID2 = paste0("Vol",from)) %>% select(from=alter_ID2,to,weight)


nodes <- alter_list %>% 
  select(ego_ID) %>% 
  distinct(ego_ID) %>% 
  rbind(nodes_vols)


#Filter for a patient
edges_1 <- edges %>% 
  filter(to == 1)

nodes_1_vols <- alter_list %>% 
  filter(ego_ID ==1) %>% 
  mutate(alter_ID2 = paste0("Vol",alter_ID)) %>% 
  distinct(alter_ID2) %>% 
  select(ego_ID = alter_ID2)
nodes_1 <- alter_list %>% 
  filter(ego_ID == 1) %>% 
  distinct(ego_ID) %>% 
  rbind(nodes_1_vols)





g <- graph_from_data_frame(d=edges_1, vertices=nodes_1, directed=FALSE)

V(g)$label <- ifelse(E(g)$weight>=10, V(g)$name, NA)
V(g)$color <- "blue"
V(g)$color <-  ifelse(V(g)$name != 1, "grey", V(g)$color)

normalize_01 <- function(x) (x - min(x)) / (max(x) - min(x)) + 0.25
V(g)$size <- normalize_01((E(g)$weight))*10

jpeg("CF_patient_graph.jpg", 
     width=6.8, height=6.8, 
     units='in',res=300)
plot.igraph(g, 
            asp = 0,
            main = "Graph of CF Patient" ,
            vertex.label.cex = .40,
     layout = layout_with_fr
     ) 
dev.off()

plot.igraph(g,asp = 0, main = "Graph of CF Patient" , vertex.label.cex = .40, layout = layout_with_fr) # change edge color to grey)

```

# Alter primacy

* Does being one of the first volunteers to meet a patient impact the number of repeat visits?

* Model is not significant but interesting negative beta/ close sig level

```{r, alter_list}
alter_primacy_model <- lm (alter_num ~ alter.clo, data =alter_list)    #This model adds in the covariate effect of th
summary(alter_primacy_model)
```


# Egocentric network analysis with inter-volunteer connections

```{r, inter-vol}
library(readxl)

# https://github.com/rstudio/cheatsheets/blob/master/data-import.pdf
#issue here with loading in-- Error: Can't combine `..1$VOL ID` <character> and `..5$VOL ID` <double>.
read_all <- function(path, ...) {

  path %>%
    readxl::excel_sheets() %>%
    rlang::set_names() %>%
    purrr::map_df(function(x) {
                      readxl::read_excel(path = path, sheet = x, ...)
                   })

}
path <- "Volunteer Visit SNA.xlsx"
all_patients <- read_all(path,col_types = "text") %>% 
  fill(ego_ID)
write_csv(all_patients,"all_patients_sna.csv")

one_patient_clean <- all_patients %>% 
  mutate(visit_ID = 1:nrow(all_patients),
         volunteer = strsplit(trimws(as.character(`VOL NAME`)), ",")) %>%
  unnest(volunteer) %>% 
  mutate(volunteer_clean = trimws(volunteer))

unique_vols <- one_patient_clean %>% 
  distinct(ego_ID,volunteer_clean) %>% 
  mutate(vol_ID = row_number())

one_patient_clean_vol_id <- left_join(one_patient_clean,unique_vols,by = c("volunteer_clean","ego_ID"))

alter_alter_list <- one_patient_clean_vol_id %>% mutate(visit_together = 1) %>%
  mutate(vol_ID2 = vol_ID) %>% 
  pivot_wider(names_from = vol_ID,values_from=visit_together) %>% 
  group_by(visit_ID) %>% 
  fill(everything()) %>% 
  ungroup() 

alter_adj_matrix <- alter_alter_list %>% 
  select(-`Date of volunteer visits`,-`VOL NAME`,-visit_ID,-volunteer)


alter_ties <- alter_adj_matrix %>% 
  group_by(vol_ID2) %>% 
  summarise(across(where(is.numeric),~ sum(.x,na.rm = TRUE)))

adj_clean <- alter_ties %>%  mutate_all(as.double) 

library(data.table)
fwrite(adj_clean,"some.name.temp")
dfm <- fread("some.name.temp",colClasses="double")
str(dfm)

m <- as.matrix(dfm, rownames = TRUE)


ig <- graph_from_adjacency_matrix(m,mode = "undirected", weighted=TRUE,diag=F)
ig


#3 egor objects

#1. ego list object
ego_list <- read_csv("Patient Ego List Final for SPSS.csv")
ego_list <- ego_list %>% 
  mutate(across(where(is.character), as.factor)) %>% 
  rename(ego_ID = `EGO Number`)


#2. Creating Alter Attributes Object of ego_ID, alter_ID, and weight of visits to each Ego
alter_attr <- alter_alter_list %>% 
  filter(ego_ID %in% unique_ego_list$ego_ID) %>% 
  select(ego_ID,vol_ID2,volunteer_clean) %>% 
  group_by(vol_ID2) %>% 
  summarise(weight = n(),
            ego_ID = ego_ID,
            volunteer_clean = volunteer_clean) %>% 
  distinct(vol_ID2,.keep_all = TRUE) %>% 
  ungroup()
unique_ego_alter_attr <- alter_attr %>% 
  distinct(ego_ID)
unique_ego_list <- ego_list %>% 
  distinct(ego_ID)


alter_attr$ego_ID <- as.numeric(alter_attr$ego_ID)
# alter-ties list
tie_list <- get.data.frame(ig) 
tie_merge_vols <- unique_vols %>% 
  rename(from = vol_ID) 
tie_merge_vols$from <- as.character(tie_merge_vols$from)
tie_list_2 <- left_join(tie_list,tie_merge_vols,by= "from") %>%
  select(-volunteer_clean,ego_ID,from,to,weight) 
tie_list_2$ego_ID <-  as.double(tie_list_2$ego_ID)
tie_list_2 <- tie_list_2 %>% 
  select(from,to,ego_ID,weight) %>% 
  filter(ego_ID %in% unique_ego_list$ego_ID) 
ego_list$ego_ID <- as.double(ego_list$ego_ID)

#Create egor object, containing alter attributes list, ego list, and tie list 

egor.obj <- egor::threefiles_to_egor(alters = alter_attr, 
                                     egos = ego_list, 
                               edges = tie_list_2, 
                               ID.vars = list(ego = "ego_ID", 
                                              alter ="vol_ID2",
                                              source = "from", 
                                              target = "to"))

egor.obj

gr.list <- summary(egor.obj)
density_tibble <- ego_density(egor.obj) 
density_tibble$.egoID <- as.double(density_tibble$.egoID)

sna_ego_list <- left_join(ego_list,density_tibble,by=c("ego_ID"=".egoID"))

sna_ego_list_for_model <- sna_ego_list %>% 
  select(ego_ID,
         network_size=`Network Size`,
         avg_alter_freq=`RQ 4Average alter closeness`,
         max_alter_freq=`RQ4alter closeness max`,
         sd_alter_freq=`RQ 4Alter Closeness SD`,
         med_alter_freq=`RQ4alter median closeness`,
         project_team=`RQ5 Project Team`,
         gender=Gender,
         deceased=Deceased,
         age=Age,
         days_in_SL=`RQ1 Time in SL`,
         avg_los=`RQ1 Average LOS`,
         total_los=`RQ1Total LOS`,
         max_los=`RQ1 Max LOS`,
         visits_per_admission=`RQ2 VISITS PER ADMISSION`,
         total_admissions=`RQ1 Total Admissions`,
         total_visits=`RQ1Total Visits`,
         density,
         dpp=`DPP?`)

write_csv(sna_ego_list_for_model,"sna_ego_list")


egor::egor_vis_app(egor.obj)

names(egor.obj$alter)

save(egor.obj, ego_list,alter_attr,tie_list_2, file="SL_SNA_egor.rda")
egor::count_dyads(egor.obj,".alt_ID",return_as = "long")


#edit name list for a few entries-- see PDF output for directors
```


